import os
import sys
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Dict, List

import markdown
import smtplib

# Add project root to path for imports
project_root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(project_root))

from agents import Agent, AgentOutputSchema
from src.config import config

INSTRUCTIONS = """You are an email formatting expert specializing in creating professional, well-designed HTML emails.
You will be provided with a detailed business report. You should:

1. Convert the markdown report to clean, professional HTML
2. Apply a modern, business-appropriate email template
3. Include proper styling for readability
4. Embed visualizations if provided
5. Create an appropriate subject line
6. Optionally attach PDF version of the report
7. Support multiple recipients if needed

The email should be professional, well-formatted, and easy to read on both desktop and mobile devices."""


def create_html_template(content: str, title: str = "Business Consultant Report") -> str:
    """Create a professional HTML email template."""
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{title}</title>
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f4f4f4;
            }}
            .email-container {{
                background-color: #ffffff;
                border-radius: 8px;
                padding: 30px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }}
            .header {{
                border-bottom: 3px solid #007bff;
                padding-bottom: 20px;
                margin-bottom: 30px;
            }}
            .header h1 {{
                color: #007bff;
                margin: 0;
                font-size: 24px;
            }}
            .content {{
                color: #555;
            }}
            .footer {{
                margin-top: 30px;
                padding-top: 20px;
                border-top: 1px solid #eee;
                color: #888;
                font-size: 12px;
                text-align: center;
            }}
        </style>
    </head>
    <body>
        <div class="email-container">
            <div class="header">
                <h1>{title}</h1>
            </div>
            <div class="content">
                {content}
            </div>
            <div class="footer">
                <p>This report was generated by the Business Consultant Agent</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html_template


def markdown_to_html(markdown_content: str) -> str:
    """Convert markdown to HTML."""
    return markdown.markdown(markdown_content, extensions=['extra', 'codehilite', 'tables'])


def send_email_smtp(
    to_email: str | None = None,
    subject: str | None = None,
    body: str | None = None,
    recipients: List[str] | None = None,
    pdf_attachment_path: str | None = None
) -> Dict[str, str | List[str]]:
    """
    Send email using SMTP.
    """
    if not config.smtp_user or not config.smtp_password:
        return {"error": "SMTP credentials missing."}

    recipients = recipients or []
    email_recipients = [to_email] if to_email else ([config.email_recipient] if config.email_recipient else [])
    email_recipients.extend(recipients)

    if not email_recipients:
        return {"error": "No recipients."}

    from_email = config.from_email or config.smtp_user

    try:
        html_content = markdown_to_html(body) if body else "<p>No content.</p>"
        html_body = create_html_template(html_content, subject or "Business Consultant Report")

        msg = MIMEMultipart('alternative')
        msg['From'] = from_email
        msg['To'] = email_recipients[0]
        if len(email_recipients) > 1:
            msg['Cc'] = ', '.join(email_recipients[1:])
        msg['Subject'] = subject or "Business Consultant Report"

        msg.attach(MIMEText(html_body, 'html'))

        if pdf_attachment_path and Path(pdf_attachment_path).exists():
            with open(pdf_attachment_path, 'rb') as f:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', f'attachment; filename= {Path(pdf_attachment_path).name}')
                msg.attach(part)

        if config.smtp_port == 465:
            server = smtplib.SMTP_SSL(config.smtp_server, config.smtp_port)
        else:
            server = smtplib.SMTP(config.smtp_server, config.smtp_port)
            if config.smtp_use_tls:
                server.starttls()

        server.login(config.smtp_user, config.smtp_password)
        server.send_message(msg)
        server.quit()

        return {"status": "success", "recipients": email_recipients}
    except Exception as e:
        return {"error": str(e)}

email_agent = Agent(
    name="EmailAgent",
    instructions=INSTRUCTIONS,
    model=config.email_model,
    output_type=AgentOutputSchema(str, strict_json_schema=False),
)
